### ISSUE TITLE
关于本文引用规范的一些建议

### ISSUE THREAD

**Issue by caiyuanhao1998** [ucaswangls/STFormer#1]
作者你好，感谢你的努力为社区带了一份好的工作。
看完你的文章，我有一些疑惑，希望能得到解答。

本文的数学记号，公式的风格与MST [1] 高度相似，尤其是3.2节包括其中算法复杂度的分析。甚至连一些MST中我特别取的名字，比如global multi-head self-attention， 甚至是简称G-MSA也是我取的。这些都被本文直接继承了。当然我也不是反对你这么做。

让我感到很疑惑的是，既然在写作上一定程度上借鉴了MST这项工作，为何没有引用并指出其贡献呢？我注意到在本文末尾的future work里面有引一些光谱SCI的文章。说明还是有关注到这一块儿的。以及 MST 是SCI领域的第一个Transformer，本文也是SCI的Transformer，于情于理，至少应该点一下其贡献吧。

当然，本文的创新性和贡献还是很棒的，如果能把引用做得更加规范和专业，那就更好了。

[1] Mask-guided Spectral-wise Transformer for Efficient Hyperspectral Image Reconstruction. In CVPR 2022.

**Comment by ucaswangls** [comment]
感谢你指出相关问题，我们将尽快在文章中完善对相关文献的应用。

**Comment by caiyuanhao1998** [comment]
感谢你的重视和解答，请问具体在什么时候能看到arxiv文章的更新呢？

**Comment by ucaswangls** [comment]
我根据你的建议在两处位置对MST进行了引用
（分别位于2.2 Vision Transformer第二段 ——PVT V2 [45] proposed a linear spatial reduction attention (SRA) layer, which uses average pooling to reduce spatial dimension, and achieve improvements on fundamental vision tasks such as classification, detection, and segmentation. MST [46] proposed a spectral-wise multi-head self-attention (S-MSA) and customized a mask-guided mechanism (MM), which effectively explores the application of Transformer to the spectral SCI task [47].
3.2.5 Computational complexity ——where Ω(·) represents the computational complexity, Gh and Gw are generally set to 7, and D is the number of frames, and compare it with the global multi-head self-
attention mechanism (G-MSA) [46]。
你帮忙看下引用位置是否合适。
如果没问题，我这今天在arxiv对文章进行更新。谢谢。

**Comment by caiyuanhao1998** [comment]
好，这很好，非常感谢。
也预祝你投稿顺利。加油！
