### ISSUE TITLE
自己采集的数据的话mask是否需要和test_datasets/mask/real_mask.mat保持一致

### ISSUE THREAD

**Issue by hopesala** [ucaswangls/STFormer#3]
也就是说算法是否对编码具有鲁棒性呢？
目前测试发现尺寸需要保持512×512，压缩率cr值为10，使用自己随机生成的mask生成的meas进行恢复，发现噪声很大，效果不太好，不知道是不是mask没有和代码中提供的mask一致的原因

请教一下作者这个问题，万分感谢～ @wanlishun66668 @ucaswangls

**Comment by hopesala** [comment]
经实验验证发现，mask需要替换成自己的实际值，是单精度single浮点数，这样背景噪声会大幅度减小

**Comment by ucaswangls** [comment]
一般来说，mask分布需要保持一致。对于分布不同的mask，需要fine-tune，用新mask迭代几个epoch就可以了。
