### ISSUE TITLE
Some problems about the code

### ISSUE THREAD

**Issue by AliLinLiang** [ucaswangls/STFormer#4]
hi, Thank you very much for your open source project!
I installed the program according to the installation manual，but when I run "python tools/test.py configs/STFormer/stformer_base.py --weights=checkpoints/stformer_base.pth"， there was a issues! I tried many times, but still couldn't solve it.  ; (

CUDA available: True
GPU numbers: 1
GPU INFO: [{'GPU 0': 'NVIDIA GeForce RTX 3090'}]
--------------------------------------------------------------------------------

/root/miniconda3/lib/python3.8/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
2023-04-27 02:09:47,140 - test.py [line: 63] - Load pre_train model...
Traceback (most recent call last):
  File "tools/test.py", line 196, in <module>
    main()
  File "tools/test.py", line 64, in main
    resume_dict = torch.load(cfg.weights)
  File "/root/miniconda3/lib/python3.8/site-packages/addict/addict.py", line 67, in __getattr__
    return self.__getitem__(item)
  File "/root/miniconda3/lib/python3.8/site-packages/addict/addict.py", line 70, in __missing__
    if object.__getattribute__(self, '__frozen'):
AttributeError: 'Config' object has no attribute '__frozen'

**Comment by ucaswangls** [comment]
It seems that there is a problem with the model weight loading, please check whether the model weight file is downloaded correctly (checkpoints/stformer_base.pth).

**Comment by AliLinLiang** [comment]
> It seems that there is a problem with the model weight loading, please check whether the model weight file is downloaded correctly (checkpoints/stformer_base.pth).

Thanks！The code can run normally now : )
